#  +-------------------------------------------------------------------------------+
#  |                          _____    ___    _____   _____                        |
#  |                         |___  |  / _ \  |  _  | /  ___\                       |
#  |                             | | | | | | | |_| | | |___                        |
#  |                          _  | | | | | | |  _ \  |___  |                       |
#  |                         | \_/ | | |_| | | |_| |  ___| |                       |
#  |                          \___/   \___/  |_____| \_____/                       |
#  |                                                                               |
#  |                                                                               |
#  |   Author: SoKnight                                           Version: 1.3.0   |
#  |                                                                               |
#  +-------------------------------------------------------------------------------+
#
# Available placeholders:
# - %jobs_worknow% - Player work now or not
# - %jobs_JOB_joined% - Joined or not player to target job (true/false)
# - %jobs_JOB_worknow% - Player work now at target job or not (true/false)
# - %jobs_JOB_level% - Job level
# - %jobs_JOB_progress% - Job level progress
# - %jobs_JOB_needed% - Job exp needed for next level
# - %jobs_JOB_basesalary% - Base salary for job
# - %jobs_JOB_permboost% - Boost from permissions

# Configuration of database
database:
  # Should plugin use MySQL Database as data storage?
  # Specify 'true' for MySQL or 'false' for SQLite
  use-mysql: false
  # MySQL configuration
  host: localhost
  port: 3306
  name: jobs
  user: admin
  password: jobs
  # SQLite configuration
  file: jobs.db

# Configuration of messages
messages:
  # Messages localization, available: [en, ru]
  # Write in discussion on spigotmc plugin or github page, if you can translate plugin to other languages
  locale: en
  # Should plugin set special prefix after all messages
  use-prefix: false
  # Prefix for all messages
  # Tip - there is no space between the prefix and the message
  prefix: "&6[Jobs] &r"
  # Unknown boost symbol for '/jobs info' with offline player argument
  unknown-boost: '?'
  # Prefix for level value in '/jobs info' when current level is max
  max-level-prefix: '&6'
  # Count of strings on one list page for '/ep .. list' commands
  list-size: 10
  # Should plugin sent salary messages to player's actionbar
  salary-actionbar: true
  # Should plugin sent messages about blocks selection to player's actionbar
  selection-actionbar: true
  # Should plugin sent levelup messages to player's title
  titled-levelup: true

# Max count of available jobs per player
# Write me on spigotmc plugin page if you need custom
# jobs count per permissions and I add this feature :)
max-jobs: 2

# Ignore unknown teleport cause (fix workspace leaving when worker break block below him)
# For example, if this fix will be disabled, when worker will break block under him and
# breaked block will be replaced to other block, player will be kicked from workspace and
# his work will be doned. Server thinks that player has been teleported and call event, which
# Jobs Watchdog will handle and done player's work. It's unpleasant server feature and so
# it need fix by ignoring unknown teleport cause from PlayerTeleportEvent.
fix-workspace-leaving: true